### ISSUE TITLE
gptq quantization fails with torch 2.2

### ISSUE THREAD

**Issue by akjindal53244** [Lightning-AI/lit-gpt#582]
Following script for model quantization: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/quantize.md#gptqint4

Command failed with `AttributeError: 'GPT' object has no attribute 'build_rope_cache'`. I tried fixing it but there are more errors later. Looks like the `model.py` was changed but changes in `quantize/gptq.py` were left out in https://github.com/Lightning-AI/lit-gpt/commit/8156ddd8b76c25d4ae32ea97fcc2ddb4fd1c9035

**Comment by carmocca** [comment]
This should be fixed by #563. Can you try with the latest version?

**Comment by akjindal53244** [comment]
@carmocca , it still fails unfortunately:

Using command from [here](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/quantize.md#gptqint4)

`python quantize/gptq.py --precision bf16-true --checkpoint_dir checkpoints/tiiuae/falcon-7b`

```
Loading model 'checkpoints/tiiuae/falcon-7b/lit_model.pth' with {'org': 'tiiuae', 'name': 'falcon-7b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'gelu_approximate': 'none', 'intermediate_size': 18176, 'rope_condense_ratio': 1, 'rope_base': 10000, 'head_size': 64, 'rope_n_elem': 64}
Time to load model: 5.95 seconds.
Using custom data configuration allenai--c4-6fbe877195f42de5
Found cached dataset json (/home/minimalist/.cache/huggingface/datasets/allenai___json/allenai--c4-6fbe877195f42de5/0.0.0/e6070c77f18f01a5ad4551a8b7edfba20b8438b7cad4d94e6ad9378022ce4aab)
GPT(
  (lm_head): Linear(in_features=4544, out_features=65024, bias=False)
  (transformer): ModuleDict(
    (wte): Embedding(65024, 4544)
    (h): ModuleList(
      (0-31): 32 x Block(
        (norm_1): LayerNorm((4544,), eps=1e-05, elementwise_affine=True)
        (attn): CausalSelfAttention(
          (attn): Linear(in_features=4544, out_features=4672, bias=False)
          (proj): Linear(in_features=4544, out_features=4544, bias=False)
        )
        (mlp): GptNeoxMLP(
          (fc): Linear(in_features=4544, out_features=18176, bias=False)
          (proj): Linear(in_features=18176, out_features=4544, bias=False)
        )
      )
    )
    (ln_f): LayerNorm((4544,), eps=1e-05, elementwise_affine=True)
  )
)
Config(org='tiiuae', name='falcon-7b', block_size=2048, vocab_size=50254, padding_multiple=512, padded_vocab_size=65024, n_layer=32, n_head=71, n_embd=4544, rotary_percentage=1.0, parallel_residual=True, bias=False, lm_head_bias=False, n_query_groups=1, shared_attention_norm=True, _norm_class='LayerNorm', norm_eps=1e-05, _mlp_class='GptNeoxMLP', gelu_approximate='none', intermediate_size=18176, rope_condense_ratio=1, rope_base=10000)
Getting inputs for first block
Starting to quantize blocks
0 attn.attn collecting stats quantizing time 2s quantization error 6767.9
0 attn.proj collecting stats python: /root/.triton/llvm/llvm+mlir-17.0.0-x86_64-linux-gnu-centos-7-release/include/llvm/ADT/SmallVector.h:294: T& llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::operator[](llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type) [with T = mlir::Value; <template-parameter-1-2> = void; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::reference = mlir::Value&; llvm::SmallVectorTemplateCommon<T, <template-parameter-1-2> >::size_type = long unsigned int]: Assertion `idx < size()' failed.
Aborted (core dumped)
```

**Comment by akjindal53244** [comment]
@carmocca gentle ping

**Comment by carmocca** [comment]
Hi @akjindal53244. I just tried this script on two different machines and it ran without issues. Perhaps there's a problem with your environment. Could you try repeating the steps in a new environment?

It could also be that your system doesn't have enough memory. GPTQ quantization is an intensive process. See https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/quantize.md#gptqint4

**Comment by carmocca** [comment]
I tried with nightly (future 2.2) and I was able to reproduce. 2.1 should work though, can you try?

```shell
pip uninstall -y torch
pip install --index-url https://download.pytorch.org/whl/test/cu118 --pre 'torch==2.1.0'
```
